output_dir: "runs/fine-tuning"
prompt: "legal graffiti . illegal graffiti ."
threshold: 0.1
seed: 42
per_device_train_batch_size: 2
per_device_eval_batch_size: 8
eval_accumulation_steps: 128
gradient_accumulation_steps: 32
num_train_epochs: 1
learning_rate: 1e-5
eval_strategy: "epoch"
eval_on_start: True
remove_unused_columns: False
weight_decay: 3e-6
adam_beta2: 0.999
optim: "adamw_torch"
save_strategy: "best"
report_to: "none"
load_best_model_at_end: True
dataloader_pin_memory: False
logging_strategy: "no"
metric_for_best_model: "f1"
greater_is_better: True
lr_scheduler_type: "cosine"
disable_tqdm: False
